# Site settings
title: Maddie Gastonguay lab notebook # type your own lablog title here

description: > # this means to ignore newlines until "baseurl:"
  This is my lab notebook for my undergraduate honors thesis in Dr. Paola Vera-Licona's
  Computational Systems Medicine Research Group.
baseurl: "/gastonguay_compsysmed_labnotebook" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
include: [ _assets , _projects ]

name : Maddie Gastonguay
email : madeleine.gastonguay@uconn.edu
github_username: MadeleineGastonguay

# Build settings
markdown: kramdown
kramdown:
  input: GFM

noindex: true # if true, google will ignore your pages!

defaults:   # overwrite with in YAML frontmatter, e.g. 'place: New York'
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      place:  # default Geolocation of posts.
      author: 'maddie' # default author for posts (for multi-authoring)
