---
title: "weight_sums_TFs"
output: html_document
---

## Instructions:
When running this file, chage working directory accordingly and make sure 5 files you're inputing are correctly named. Then uncomment the ggsave function and change the name of the image you're saving.


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## input files



```{r}

setwd("~/Documents/GitHub/gastonguay_compsysmed_labnotebook/_projects/project1")
# setwd("~/GitHub/gastonguay_compsysmed_labnotebook/_projects/project1")
library(readr)
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(knitr)
library(gridExtra)
library(grid)

#Input Files:
AP500<-read.csv("gene_network/TF_0500_expr_openchrom_unmeth.txt", header = FALSE)
AP1000<-read.csv("gene_network/TF_1000_expr_openchrom_unmeth.txt", header = FALSE)
AP1500<-read.csv("gene_network/TF_1500_expr_openchrom_unmeth.txt", header = FALSE)
AP2000<-read.csv("gene_network/TF_2000_expr_openchrom_unmeth.txt", header = FALSE)
AP2500<-read.csv("gene_network/TF_2500_expr_openchrom_unmeth.txt", header = FALSE)

#Lists we're comparing to:
HOC<- read.csv("HOC.txt", header = FALSE)
CL<-read.csv("EMT_innateimmune", header = FALSE)
breastDO <-read.csv("breast_DO.txt", header = FALSE)
```

#calculate weighted sums
```{r}
weightedsums<-data.frame(promoter_window = NA, number_genes = NA, HOC_num= NA, HOC_perc= NA, breastDO_num= NA, breastDO_perc= NA, CLgenes_num=NA, CLgenes_perc=NA, sum=NA)
class(weightedsums$sum)<-'numeric'

varlist<-list(AP500$V1,AP1000$V1,AP1500$V1,AP2000$V1,AP2500$V1)
for (i in varlist){
  ilen<-length(i)
  a<-length(intersect(i,HOC$V1))
  b<-length(intersect(i,breastDO$V1))
  c<-length(intersect(i,CL$V1))
  x<-length(intersect(i,HOC$V1))/ilen
  y<-length(intersect(i,breastDO$V1))/ilen
  z<-length(intersect(i,CL$V1))/ilen
  SUM<-((1/3)*x)+((1/3)*y)+((1/3)*z)
  weightedsums[nrow(weightedsums)+1,] = list(NA,ilen,a,x,b,y,c,z,SUM)
}
weightedsums<-weightedsums[-1,]
weightedsums[1,1]<-'500'
weightedsums[2,1]<-'1000'
weightedsums[3,1]<-'1500'
weightedsums[4,1]<-'2000'
weightedsums[5,1]<-'2500'

# write.table(weightedsums,"gene_network/weightedsums_TF.txt", row.names=FALSE, quote = FALSE)

weightedsums2 <- weightedsums[,c(1,2,4,6,8,9)]
weightedsums2$rounded_sum <- round(weightedsums$sum, 4)

positions <- c("500", "1000", "1500", "2000", "2500")

g1 <- ggplot(data= weightedsums2, aes(x = promoter_window, y =sum)) + geom_bar(stat="identity", aes(fill = promoter_window)) +
  scale_x_discrete(limits = positions) +
  geom_text(aes(label = rounded_sum), vjust=1.6, color="white", size=3.5) +
  ggtitle("Transcription Factor Weighted Sums") + xlab("Promotor Window Size") +ylab("Weighted Sum") + theme(legend.position = "none")

tt <- ttheme_default(colhead=list(fg_params = list(fontface=c( "bold"))),
                     # fg_params=list(fontface=c(rep("plain", 4), "bold.italic")),
                     base_size = 7.5,
                     padding = unit(c(2, 4), "mm"))
tbl <- tableGrob(weightedsums, rows=NULL, theme = tt)

# ggsave("../../_assets/images/weightedsums_TF_graph_table.png", arrangeGrob(g1, tbl, nrow = 2, heights = c(3,1)), "png")

## setwd("~/GitHub/gastonguay_compsysmed_labnotebook/_assets/images")
## ggsave("../../_assets/images/weightedsums_TF.png", g1, "png")

```
